<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_ValueResolver_Prestashop_FiltersBuilder_ResolverService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.debug.value_resolver.prestashop.filters_builder.resolver' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.filters_builder.resolver'] ?? $container->load('getPrestashop_FiltersBuilder_ResolverService'));

        if (isset($container->privates['.debug.value_resolver.prestashop.filters_builder.resolver'])) {
            return $container->privates['.debug.value_resolver.prestashop.filters_builder.resolver'];
        }

        return $container->privates['.debug.value_resolver.prestashop.filters_builder.resolver'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver($a, ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
