<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GX_NX_SService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gX.nX.s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gX.nX.s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formBuilder' => ['services', 'prestashop.core.form.identifiable_object.builder.tag_form_builder', 'getPrestashop_Core_Form_IdentifiableObject_Builder_TagFormBuilderService', true],
            'formHandler' => ['services', 'prestashop.core.form.identifiable_object.tag_form_handler', 'getPrestashop_Core_Form_IdentifiableObject_TagFormHandlerService', true],
        ], [
            'formBuilder' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Builder\\FormBuilderInterface',
            'formHandler' => 'PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\Handler\\FormHandlerInterface',
        ]);
    }
}
