<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AEvSyC9Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aEvSyC9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aEvSyC9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discountFactory' => ['services', 'prestashop.core.grid.grid_factory.discount', 'getPrestashop_Core_Grid_GridFactory_DiscountService', true],
            'discountFilters' => ['privates', '.errored..service_locator.aEvSyC9.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\DiscountFilters', NULL, 'Cannot autowire service ".service_locator.aEvSyC9": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\DiscountFilters" but no such service exists.'],
        ], [
            'discountFactory' => 'PrestaShop\\PrestaShop\\Core\\Grid\\GridFactoryInterface',
            'discountFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\DiscountFilters',
        ]);
    }
}
