<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_GLY6u1fService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.GLY6u1f' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.GLY6u1f'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\UpdateDiscountConditionsHandler(new \PrestaShop\PrestaShop\Adapter\Discount\Update\DiscountConditionsUpdater(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'] ?? $container->load('getDiscountRepositoryService')), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), 'ps_')))->handle(...), ['method' => 'handle']);
    }
}
