<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_JnooMeCService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.JnooMeC' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.JnooMeC'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Discount\CommandHandler\AddDiscountHandler(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'] ?? $container->load('getDiscountRepositoryService')), new \PrestaShop\PrestaShop\Adapter\CartRule\CartRuleBuilder(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountTypeRepository'] ?? $container->load('getDiscountTypeRepositoryService'))), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Validate\\DiscountValidator'] ?? $container->load('getDiscountValidatorService'))))->handle(...), ['method' => 'handle']);
    }
}
