<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_EJHMAt9Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.eJHMAt9' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.eJHMAt9'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Shipment\QueryHandler\GetShipmentForViewingHandler(($container->services['PrestaShopBundle\\Entity\\Repository\\ShipmentRepository'] ?? $container->load('getShipmentRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Order\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Carrier\\Repository\\CarrierRepository'] ?? $container->load('getCarrierRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Country\\Repository\\CountryRepository'] ?? self::getCountryRepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Address\\Repository\\AddressRepository'] ?? $container->load('getAddressRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\State\\Repository\\StateRepository'] ?? $container->load('getStateRepositoryService'))))->handle(...), ['method' => 'handle']);
    }
}
