<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZTfSn78Service extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZTfSn78' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZTfSn78'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderDetailRepository' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Order\\Repository\\OrderDetailRepository', 'getOrderDetailRepositoryService', true],
        ], [
            'orderDetailRepository' => 'PrestaShop\\PrestaShop\\Adapter\\Order\\Repository\\OrderDetailRepository',
        ]);
    }
}
