<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountFiltersService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aEvSyC9.PrestaShop\PrestaShop\Core\Search\Filters\DiscountFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\DiscountFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aEvSyC9": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\DiscountFilters" but no such service exists.');
    }
}
