<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountProductSegmentValidatorService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\ConstraintValidator\DiscountProductSegmentValidator' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\ConstraintValidator\DiscountProductSegmentValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\ConstraintValidator\\DiscountProductSegmentValidator'] = new \PrestaShop\PrestaShop\Core\ConstraintValidator\DiscountProductSegmentValidator(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
