<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountValidatorService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Validate\\DiscountValidator'] = $instance = new \PrestaShop\PrestaShop\Adapter\Discount\Validate\DiscountValidator(($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));

        $instance->setDiscountRepository(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountRepository'] ?? $container->load('getDiscountRepositoryService')));

        return $instance;
    }
}
