<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryConditionsTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Discount\DeliveryConditionsType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Discount\DeliveryConditionsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Discount\\DeliveryConditionsType'] = new \PrestaShopBundle\Form\Admin\Sell\Discount\DeliveryConditionsType(($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(false));
    }
}
