<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiscountFormDataProviderService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\DiscountFormDataProvider' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\DiscountFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.query_bus'] ?? $container->load('getPrestashop_Core_QueryBusService'));

        if (isset($container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\DiscountFormDataProvider'])) {
            return $container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\DiscountFormDataProvider'];
        }

        return $container->services['PrestaShop\\PrestaShop\\Core\\Form\\IdentifiableObject\\DataProvider\\DiscountFormDataProvider'] = new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataProvider\DiscountFormDataProvider($a, ($container->services['PrestaShop\\PrestaShop\\Adapter\\Product\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Product\\Combination\\Repository\\CombinationRepository'] ?? $container->load('getCombinationRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Product\\Combination\\NameBuilder\\CombinationNameBuilderInterface'] ?? $container->load('getCombinationNameBuilderInterfaceService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Domain\\Product\\Image\\Provider\\ProductImageProviderInterface'] ?? $container->load('getProductImageProviderInterfaceService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Attribute\\Repository\\AttributeRepository'] ?? $container->load('getAttributeRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\Repository\\FeatureValueRepository'] ?? $container->load('getFeatureValueRepositoryService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? self::getShopContextService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountTypeRepository'] ?? $container->load('getDiscountTypeRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Customer\\Repository\\CustomerRepository'] ??= new \PrestaShop\PrestaShop\Adapter\Customer\Repository\CustomerRepository()));
    }
}
