<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnrichedChoiceTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Type\EnrichedChoiceType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Type\EnrichedChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Type\\EnrichedChoiceType'] = new \PrestaShopBundle\Form\Admin\Type\EnrichedChoiceType(NULL, ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
