<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditShipmentTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Order\Shipment\EditShipmentType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Order\Shipment\EditShipmentType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Form\\ChoiceProvider\\AvailableCarriersForShipmentChoiceProvider'] ?? $container->load('getAvailableCarriersForShipmentChoiceProviderService'));

        if (isset($container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Shipment\\EditShipmentType'])) {
            return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Shipment\\EditShipmentType'];
        }

        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Shipment\\EditShipmentType'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Shipment\EditShipmentType($a, ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
