<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMergeShipmentTypeService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private 'PrestaShopBundle\Form\Admin\Sell\Order\Shipment\MergeShipmentType' shared autowired service.
     *
     * @return \PrestaShopBundle\Form\Admin\Sell\Order\Shipment\MergeShipmentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Form\\Admin\\Sell\\Order\\Shipment\\MergeShipmentType'] = new \PrestaShopBundle\Form\Admin\Sell\Order\Shipment\MergeShipmentType(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
