<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Form_IdentifiableObject_Handler_DiscountFormHandlerService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.core.form.identifiable_object.handler.discount_form_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.form.identifiable_object.handler.discount_form_handler'] = ($container->services['prestashop.core.form.identifiable_object.handler.form_handler_factory'] ?? $container->load('getPrestashop_Core_Form_IdentifiableObject_Handler_FormHandlerFactoryService'))->create(new \PrestaShop\PrestaShop\Core\Form\IdentifiableObject\DataHandler\DiscountFormDataHandler(($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService')), ($container->privates['prestashop.default.language.context'] ?? self::getPrestashop_Default_Language_ContextService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['PrestaShop\\PrestaShop\\Adapter\\Discount\\Repository\\DiscountTypeRepository'] ?? $container->load('getDiscountTypeRepositoryService'))));
    }
}
