<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_FiltersBuilder_ResolverService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the public 'prestashop.filters_builder.resolver' shared service.
     *
     * @return \PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.search.builder'] ?? $container->load('getPrestashop_Core_Search_BuilderService'));

        if (isset($container->services['prestashop.filters_builder.resolver'])) {
            return $container->services['prestashop.filters_builder.resolver'];
        }

        return $container->services['prestashop.filters_builder.resolver'] = new \PrestaShopBundle\Controller\ArgumentResolver\FiltersBuilderResolver($a);
    }
}
