<?php

namespace ContainerIw3WgcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipmentFiltersService extends AdminKernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v6SDqDc.PrestaShop\PrestaShop\Core\Search\Filters\ShipmentFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\ShipmentFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.v6SDqDc": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ShipmentFilters" but no such service exists.');
    }
}
