<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIw3WgcT\AdminKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIw3WgcT/AdminKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIw3WgcT.legacy');

    return;
}

if (!\class_exists(AdminKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIw3WgcT\AdminKernelDevDebugContainer::class, AdminKernelDevDebugContainer::class, false);
}

return new \ContainerIw3WgcT\AdminKernelDevDebugContainer([
    'container.build_hash' => 'Iw3WgcT',
    'container.build_id' => 'c987b678',
    'container.build_time' => 1763043908,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIw3WgcT');
